version: '3.8'

services:
  rag-chatbot:
    build: .
    ports:
      - "8501:8501"
    volumes:
      # Persistent data storage
      - ./data:/app/data
      # Optional: Override configuration
      - ./.env:/app/.env:ro
    environment:
      # =============================================================================
      # HYBRID API Configuration - DeepSeek LLM + OpenAI Embeddings
      # =============================================================================
      # Required API Keys
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}  # For LLM
      - OPENAI_API_KEY=${OPENAI_API_KEY}      # For embeddings (DeepSeek doesn't provide embedding API)
      
      # Optional overrides
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - RUNNING_IN_DOCKER=true
      
      # Paths (using mounted volumes)
      - APP_DATA_DIR=/app/data
      - CHROMA_DB_PATH=/app/data/chroma_database
      - SAMPLE_DOCS_DIR=/app/data/sample_docs
      - UPLOAD_DIR=/app/data/uploads
      
      # =============================================================================
      # Model configuration - HYBRID: OPENAI EMBEDDINGS + DEEPSEEK LLM
      # =============================================================================
      # Embedding model (OpenAI - DeepSeek doesn't offer embedding API)
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-text-embedding-3-small}
      
      # LLM model (DeepSeek)
      - DEFAULT_LLM_MODEL=${DEFAULT_LLM_MODEL:-deepseek-chat}
      
      # RAG parameters (optional)
      - CHUNK_SIZE=${CHUNK_SIZE:-500}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP:-100}
      - N_RESULTS=${N_RESULTS:-3}
      
      # =============================================================================
      # LLM parameters - ADJUSTED FOR DEEPSEEK CAPABILITIES
      # =============================================================================
      # DeepSeek parameters (increased defaults for better capability)
      - LLM_MAX_TOKENS=${LLM_MAX_TOKENS:-512}  # Increased from 256
      - LLM_TEMPERATURE=${LLM_TEMPERATURE:-0.2}
      - LLM_TOP_P=${LLM_TOP_P:-1.0}
      
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Resource limits (optional)
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M

# Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - rag-chatbot
  #   restart: unless-stopped

volumes:
  # Named volumes for better management (alternative to bind mounts)
  rag_data:
    driver: local 